import test from 'node:test';
import assert from 'node:assert/strict';
import {act,createGame,joinGame,view,CARDS,POOL,POOL_COUNTS,drawHand} from '../engine.mjs';
const card=(id,type,hp=CARDS[type].hp,extra={})=>({id,type,hp,sleep:0,...extra});
function battle(){const g=createGame('甲');joinGame(g,'乙');Object.assign(g,{phase:'battle',turn:0,ap:1,round:1});for(const p of g.players){p.hand=[];p.field=[null,null,null,null];p.discard=[];}g.players[0].field[3]=card('anchor0','sloth');g.players[1].field[3]=card('anchor1','sloth');return g;}
function advance(g){g.players[g.turn].passes=0;act(g,g.turn,{type:'pass'});}
const skill=(g,i,id,extra={})=>act(g,i,{type:'skill',actorId:id,...extra});
const attack=(g,i,id,targetId)=>act(g,i,{type:'attack',actorId:id,targetId});
const control=(g,id,targetId,action)=>act(g,0,{type:'control',actorId:id,targetId,action});

test('十一种卡按数量表进入42张共享牌堆，随机手牌仍有三张可摆牌',()=>{assert.equal(POOL.length,42);assert.deepEqual(POOL_COUNTS,{starfish:2,seahorse:2,shark:3,kangaroo:3,crab:4,whale:4,urchin:4,elephant:4,sloth:5,penguin:5,sunfish:6});for(let k=0;k<50;k++){const hand=drawHand();assert.equal(hand.length,6);assert.ok(hand.filter(t=>CARDS[t].kind!=='once').length>=3);}});
test('双方各抽六张后只剩30张，发出的牌与余牌总量符合共享牌堆',()=>{for(let k=0;k<50;k++){const g=createGame('甲');assert.equal(g.deck.length,36);joinGame(g,'乙');assert.equal(g.deck.length,30);for(const p of g.players){assert.equal(p.hand.length,6);assert.ok(p.hand.filter(c=>CARDS[c.type].kind!=='once').length>=3);}const types=[...g.players.flatMap(p=>p.hand.map(c=>c.type)),...g.deck];for(const [type,n] of Object.entries(POOL_COUNTS))assert.equal(types.filter(t=>t===type).length,n);assert.equal(view(g,0).deck,undefined);}});
test('睡眠覆盖目标两次回合，在施加者第二次回合开始解除',()=>{
  const g=battle();g.players[0].field[0]=card('sloth','sloth');g.players[1].field[0]=card('target','kangaroo',2,{airborne:true,gravity:1});
  skill(g,0,'sloth',{targetId:'target'});assert.equal(g.turn,1);assert.equal(g.round,2);assert.equal(g.players[1].field[0].sleep,2);assert.equal(g.players[1].field[0].gravity,1);
  assert.throws(()=>attack(g,1,'target','sloth'),/睡眠/);advance(g);assert.equal(g.round,3);assert.throws(()=>attack(g,0,'sloth','target'),/睡眠/);advance(g);
  assert.equal(g.round,4);assert.equal(g.players[1].field[0].sleep,1);assert.equal(g.players[1].field[0].gravity,1);advance(g);assert.equal(g.round,5);assert.equal(g.players[1].field[0].sleep,0);
  advance(g);assert.equal(g.players[1].field[0].gravity,2);
});
test('一次性树懒使用相同的两次目标回合睡眠计时',()=>{const g=battle();g.players[0].hand=[{id:'once',type:'sloth'}];g.players[1].field[0]=card('target','crab');act(g,0,{type:'once',cardId:'once',row:0});assert.equal(g.ap,1);assert.equal(g.players[1].field[0].sleepUntil,5);advance(g);advance(g);advance(g);assert.ok(g.players[1].field[0].sleep);advance(g);assert.equal(g.players[1].field[0].sleep,0);});
test('袋鼠立即获得势能，按持有者回合累积且最多三层',()=>{const g=battle();g.players[0].field[0]=card('roo','kangaroo');skill(g,0,'roo');assert.equal(g.players[0].field[0].gravity,1);advance(g);assert.equal(g.players[0].field[0].gravity,2);advance(g);advance(g);assert.equal(g.players[0].field[0].gravity,3);advance(g);advance(g);assert.equal(g.players[0].field[0].gravity,3);});
test('袋鼠落击按原射程造成势能伤害，消耗一点并解除腾空',()=>{const g=battle();g.players[0].field[0]=card('roo','kangaroo',2,{airborne:true,gravity:2});g.players[1].field[0]=card('target','elephant');skill(g,0,'roo',{targetId:'target'});assert.equal(g.players[1].field[0],null);assert.equal(g.players[1].discard[0].hp,0);assert.equal(g.players[0].field[0].airborne,undefined);assert.equal(g.turn,1);});
test('袋鼠受伤立即反击，致命伤也结算反击',()=>{const g=battle();g.turn=1;g.players[0].field[0]=card('roo','kangaroo',1,{airborne:true,gravity:2});g.players[1].field[0]=card('src','elephant');attack(g,1,'src','roo');assert.equal(g.players[0].field[0],null);assert.equal(g.players[1].field[0],null);assert.equal(g.players[0].discard[0].airborne,undefined);assert.equal(g.players[1].discard[0].hp,0);});
test('企鹅挡下伤害时袋鼠不解除腾空；无效响应不破坏队列',()=>{const g=battle();g.players[0].field[0]=card('src','crab');g.players[1].field[0]=card('roo','kangaroo',2,{airborne:true,gravity:3});g.players[1].field[1]=card('guard','penguin');attack(g,0,'src','roo');assert.equal(g.pending.respondTo,1);const before=structuredClone(g);assert.throws(()=>act(g,1,{type:'intercept',penguinId:'src'}),/挡伤/);assert.deepEqual(g,before);act(g,1,{type:'intercept',penguinId:'guard'});assert.equal(g.players[1].field[0].gravity,3);assert.equal(g.players[1].field[0].hp,2);assert.equal(g.players[1].field[1].hp,2);});
test('大象不能压制友方，压制敌方清空睡眠、腾空并禁止操作',()=>{const g=battle();g.players[0].field[0]=card('ele','elephant');g.players[1].field[0]=card('roo','kangaroo',2,{sleep:2,sleepUntil:5,airborne:true,gravity:3});const before=structuredClone(g);assert.throws(()=>skill(g,0,'ele',{targetId:'anchor0'}),/敌方/);assert.deepEqual(g,before);skill(g,0,'ele',{targetId:'roo'});const c=g.players[1].field[0];assert.equal(c.sleep,0);assert.equal(c.airborne,undefined);assert.equal(c.gravity,undefined);assert.equal(c.suppressedBy,'ele');assert.equal(g.covering[0].c.id,'ele');assert.equal(g.players[0].field[0],null);assert.throws(()=>attack(g,1,'roo','anchor0'),/压制/);assert.equal(view(g,1).covering[0].p,0);});
test('大象受击后海胆反伤来源是大象，免费返回由持有者选择',()=>{const g=battle();g.players[0].field[0]=card('ele','elephant');g.players[1].field[0]=card('spike','urchin');g.players[1].field[1]=card('src','crab');skill(g,0,'ele',{targetId:'spike'});attack(g,1,'src','spike');assert.equal(g.players[1].field[0].hp,1);assert.equal(g.players[1].field[1].hp,2);assert.equal(g.players[1].field[0].suppressedBy,undefined);assert.equal(g.pending.kind,'return');assert.equal(g.pending.respondTo,0);assert.equal(g.pending.returns[0].c.hp,1);const before=structuredClone(g);assert.throws(()=>act(g,1,{type:'return',slot:0}),/指定玩家/);assert.deepEqual(g,before);act(g,0,{type:'return',slot:2});assert.equal(g.players[0].field[2].id,'ele');assert.equal(g.players[0].field[2].hp,1);assert.equal(g.round,3);assert.equal(g.ap,1);assert.equal(g.pending,null);});
test('大象主动返回耗点，不对被压牌造成伤害',()=>{const g=battle();g.players[0].field[0]=card('ele','elephant');g.players[1].field[0]=card('target','kangaroo');skill(g,0,'ele',{targetId:'target'});advance(g);skill(g,0,'ele',{slot:1});assert.equal(g.players[0].field[1].id,'ele');assert.equal(g.players[1].field[0].hp,2);assert.equal(g.players[1].field[0].suppressedBy,undefined);assert.equal(g.turn,1);assert.equal(g.covering.length,0);});
test('大象没有返回空位时死亡，并释放被压牌',()=>{const g=battle();g.players[0].field[0]=card('ele','elephant');g.players[1].field[0]=card('target','crab');g.players[1].field[1]=card('src','crab');skill(g,0,'ele',{targetId:'target'});for(let s=0;s<3;s++)g.players[0].field[s]=card('fill'+s,'sloth');attack(g,1,'src','target');assert.equal(g.pending,null);assert.ok(g.players[0].discard.some(c=>c.id==='ele'));assert.equal(g.players[1].field[0].suppressedBy,undefined);});
test('大象叠压时逐层释放和返回，不遗留无法操作的牌',()=>{const g=battle();g.players[0].field[0]=card('a','elephant');g.players[0].field[1]=card('src','crab');g.players[1].field[0]=card('base','urchin');g.players[1].field[1]=card('b','elephant');skill(g,0,'a',{targetId:'base'});skill(g,1,'b',{targetId:'a'});assert.equal(g.covering.length,2);attack(g,0,'src','base');assert.equal(g.covering.length,0);assert.equal(g.players[1].field[0].hp,1);assert.equal(g.pending.respondTo,1);act(g,1,{type:'return',slot:1});assert.equal(g.pending.respondTo,0);act(g,0,{type:'return',slot:0});assert.equal(g.players[0].field[0].hp,1);assert.equal(g.players[1].field[1].hp,2);assert.equal(g.pending,null);});
test('海马偷走大象会释放被压制的牌，偷走被压牌会让大象返回',()=>{for(const stealBase of [false,true]){const g=battle();g.players[0].field[0]=card('ele','elephant');g.players[1].field[0]=card('base','crab');skill(g,0,'ele',{targetId:'base'});if(stealBase){advance(g);g.players[0].hand=[{id:'horse',type:'seahorse'}];act(g,0,{type:'once',cardId:'horse',targetId:'base'});assert.equal(g.pending.kind,'return');act(g,0,{type:'return',slot:0});assert.equal(g.players[0].field[0].id,'ele');}else{g.players[1].hand=[{id:'horse',type:'seahorse'}];act(g,1,{type:'once',cardId:'horse',targetId:'ele'});assert.equal(g.players[1].field[0].suppressedBy,undefined);assert.equal(g.players[1].hand[0].type,'elephant');}assert.equal(g.covering.length,0);}});
test('鲸操控攻击自己的友方，反伤仍归被操控牌，不改变持有者',()=>{const g=battle();g.players[0].field[0]=card('whale','whale');g.players[1].field[0]=card('src','crab');g.players[1].field[1]=card('spike','urchin');control(g,'whale','src',{type:'attack',actorId:'src',targetId:'spike'});assert.equal(g.players[1].field[1].hp,1);assert.equal(g.players[1].field[0].hp,1);assert.equal(g.players[0].field[0].hp,2);assert.equal(g.turn,1);});
test('鲸操控时保留物理射程，不能后排打对方后排',()=>{const g=battle();g.players[0].field[0]=card('whale','whale');g.players[1].field[2]=card('src','crab');const before=structuredClone(g);assert.throws(()=>control(g,'whale','src',{type:'attack',actorId:'src',targetId:'anchor0'}),/范围/);assert.deepEqual(g,before);control(g,'whale','src',{type:'attack',actorId:'src',targetId:'anchor1'});assert.equal(g.players[1].field[3].hp,1);assert.equal(g.players[1].field[2].id,'src');});
test('鲸不能使用免费技能，不能操作睡眠或压制牌',()=>{const g=battle();g.players[0].field[0]=card('whale','whale');g.players[1].field[0]=card('crab','crab');const before=structuredClone(g);assert.throws(()=>control(g,'whale','crab',{type:'skill',actorId:'crab'}),/耗/);assert.deepEqual(g,before);g.players[1].field[0].sleep=2;assert.throws(()=>control(g,'whale','crab',{type:'attack',actorId:'crab',targetId:'whale'}),/操作/);g.players[1].field[0].sleep=0;g.players[1].field[0].suppressedBy='x';assert.throws(()=>control(g,'whale','crab',{type:'attack',actorId:'crab',targetId:'whale'}),/操作/);});
test('鲸操控袋鼠和大象技能，总共只耗一点',()=>{for(const type of ['kangaroo','elephant']){const g=battle();g.ap=2;g.players[0].field[0]=card('whale','whale');g.players[1].field[0]=card('src',type);control(g,'whale','src',{type:'skill',actorId:'src',...(type==='elephant'?{targetId:'anchor0'}:{})});assert.equal(g.ap,1);if(type==='kangaroo')assert.equal(g.players[1].field[0].gravity,1);else{assert.equal(g.covering[0].p,1);assert.equal(g.players[0].field[3].suppressedBy,'src');}}});
test('鲸操控同阵营伤害仍可由该方企鹅挡伤',()=>{const g=battle();g.players[0].field[0]=card('whale','whale');g.players[1].field[0]=card('src','crab');g.players[1].field[1]=card('target','kangaroo');g.players[1].field[2]=card('guard','penguin');control(g,'whale','src',{type:'attack',actorId:'src',targetId:'target'});assert.equal(g.pending.respondTo,1);act(g,1,{type:'intercept',penguinId:'guard'});assert.equal(g.players[1].field[1].hp,2);assert.equal(g.players[1].field[2].hp,2);assert.equal(g.turn,1);});
test('鲸可以借用另一鲸再操控，但不能形成循环；共耗一点',()=>{const g=battle();g.ap=2;g.players[0].field[0]=card('a','whale');g.players[0].field[1]=card('src','crab');g.players[1].field[0]=card('b','whale');assert.throws(()=>control(g,'a','b',{type:'control',actorId:'b',targetId:'a',action:{type:'attack',actorId:'a',targetId:'b'}}),/循环/);control(g,'a','b',{type:'control',actorId:'b',targetId:'src',action:{type:'attack',actorId:'src',targetId:'anchor0'}});assert.equal(g.ap,1);assert.equal(g.players[0].field[3].hp,1);});
test('复活新卡清空状态，玩家视图继续隐藏敌方手牌',()=>{const g=battle();g.players[0].hand=[{id:'star',type:'starfish'}];g.players[1].hand=[{id:'secret',type:'whale'}];g.players[1].discard=[card('dead','kangaroo',0,{sleep:1,sleepUntil:5,airborne:true,gravity:3,suppressedBy:'old'})];act(g,0,{type:'once',cardId:'star',discardId:'dead',slot:0});const c=g.players[0].field[0];assert.equal(c.hp,2);assert.equal(c.airborne,undefined);assert.equal(c.suppressedBy,undefined);assert.equal(c.sleep,0);assert.equal(view(g,0).players[1].hand,undefined);});
test('鲨鱼追击不会选中睡眠牌，且群攻仍受射程约束',()=>{const g=battle();g.players[0].field[0]=card('shark','shark');g.players[1].field[0]=card('weak','crab',1);g.players[1].field[2]=card('sleeping','elephant',3,{sleep:2,sleepUntil:5});skill(g,0,'shark',{row:0});assert.equal(g.players[1].field[0],null);assert.equal(g.players[1].field[2].hp,3);assert.equal(g.players[1].field[3].hp,1);const h=battle();h.players[0].field[2]=card('shark','shark');const before=structuredClone(h);assert.throws(()=>skill(h,0,'shark',{row:1}),/可攻击/);assert.deepEqual(h,before);});
test('鲸操控压制中的大象主动返回，返回原持有者空位且仅耗一点',()=>{const g=battle();g.players[0].field[0]=card('whale','whale');g.players[1].field[0]=card('ele','elephant');g.turn=1;skill(g,1,'ele',{targetId:'anchor0'});g.ap=2;control(g,'whale','ele',{type:'skill',actorId:'ele',slot:2});assert.equal(g.ap,1);assert.equal(g.players[1].field[2].id,'ele');assert.equal(g.players[0].field[3].suppressedBy,undefined);assert.equal(g.players[0].field[3].hp,2);assert.equal(g.covering.length,0);});
test('压制中的大象只允许其敌对方攻击，鲸不能借敌牌打己方压制格',()=>{const g=battle();g.players[0].field[0]=card('ele','elephant');g.players[0].field[1]=card('whale','whale');g.players[1].field[0]=card('base','crab');g.players[1].field[1]=card('src','kangaroo');skill(g,0,'ele',{targetId:'base'});advance(g);const before=structuredClone(g);assert.throws(()=>control(g,'whale','src',{type:'attack',actorId:'src',targetId:'base'}),/大象/);assert.deepEqual(g,before);});
